### ISSUE TITLE
Value cannot be null. (Parameter 'arg0') on CountAsync MockQueryable Core

### ISSUE THREAD

**Issue by johnbyronent** [romantitov/MockQueryable#21]
Hi

I'm using the MockQueryable.Core 3.0.1

I'm trying to a CountAsync  on TestAsyncEnumerable<T> and get a Value cannot be null. (Parameter 'arg0')

[UnitTest.zip](https://github.com/romantitov/MockQueryable/files/3718566/UnitTest.zip)

Normal enumeration does work.

I've included a sample

**Comment by romantitov** [comment]
TestAsyncEnumerable from `MockQueryable.Core` required proper initialization. That's why I made packages for Moq, NSubstitute or FakeItEasy. I would recommend you to use one of these  packages 
You can see example of the initialization [here](https://github.com/romantitov/MockQueryable/blob/master/src/MockQueryable/MockQueryable.Moq/MoqExtensions.cs). In [samples](https://github.com/romantitov/MockQueryable/tree/master/src/MockQueryable/MockQueryable.Sample) you can find example of testing  CountAsync
