### ISSUE TITLE
FindAsync is not working properly

### ISSUE THREAD

**Issue by risogolo** [romantitov/MockQueryable#33]
I saw it, similar has been discussed already, but it does still not work on my end

I have 
```
var countries = CountryStub.GetCountries().AsQueryable().BuildMockDbSet(); // 3 items (1st is Id:1)
            _uow.Setup(x => x.Context.Set<Country>()).Returns(countries.Object);
            _uow.Setup(x => x.Context.Set<Country>().FindAsync(1)).ReturnsAsync(new Country { Id:1 }); // and I dont want to do this, collection contains that item already
            var repository = new CountryRepository(_uow.Object);
            var result = await repository.FindByIdAsync(1); //it calls FindAsync internally and result is null
```
and I would expect once I mock context Country that FindAsync method should return item with id:1

**Comment by romantitov** [comment]
@risogolo  thanks for the issue. I'm not sure that `_uow.Setup(x => x.Context.Set<Country>().FindAsync(1)).ReturnsAsync(new Country { Id:1 })` is proper way how FindAsync should be configured. I would suggest you more carefully have a look similar issue  https://github.com/romantitov/MockQueryable/issues/7 wit code example. 
in short, try to set up FindAsync  for `countries` instead of  `_uow`. Please let me know if it helped.

**Comment by risogolo** [comment]
Im sorry it still does not work on my side

 var countries = CountryStub.GetCountries().AsQueryable().BuildMockDbSet(); // GetCountries()r returns List<Country>
            countries.Setup(x=>x.FindAsync(1)).ReturnsAsync((object[] ids) =>
            {
                return countries.Object.FirstOrDefault(x => x.Id == 1);
            });
            _uow.Setup(x => x.Context.Set<Country>()).Returns(countries.Object);
            var repository = new CountryRepository(_uow.Object); //passing mocked context wrapped in UOW
            var result = await repository.FindByIdAsync(1); //internally calls FindAsync(id)
            Assert.IsNotNull(result); //still null

**Comment by romantitov** [comment]
@risogolo instead of `return countries.Object.FirstOrDefault(x => x.Id == 1);` I would suggest `CountryStub.GetCountries().FirstOrDefault(x => x.Id == 1);` because FindAsync should return items from real data, you can also see it in my example #7 

Not sure if the line will work:
`_uow.Setup(x => x.Context.Set<Country>()).Returns(countries.Object);` not sure if the part of code `x.Context.Set<Country>()` will return you your mock object. I would suggest you to implement IOrderManagerUnitOfWork<OrderManagerContext> in a test class and then use it in your tests. Something like this:
```
internal class MyTestClass: IOrderManagerUnitOfWork<OrderManagerContext>{
    DbSet<Country> _countryDbset;
   public MyTestClass(DbSet<Country> countryDbset){
           _countryDbset = countryDbset;
    }
   ...
    public Set<Country>
   {
         get{
               return _countryDbset;
          }
   }
   ...
} 
```

**Comment by risogolo** [comment]
so the first suggestion does not work and I will try another one later

**Comment by risogolo** [comment]
but this works
```
 countries.Setup(x => x.FindAsync(**It.IsAny<object[]>()**)).ReturnsAsync((object[] ids) =>
            {
                return CountryStub.GetCountries().FirstOrDefault(x => x.Id == 1);
            }); 
```

**Comment by romantitov** [comment]
If you can provide full code, I'll help you more. but looks like the issue is not related to the project.

**Comment by romantitov** [comment]
@risogolo  `FindAsync(It.IsAny<object[]>()` works as expected for me.
```
  var mock = users.AsQueryable().BuildMockDbSet();
      mock.Setup(x => x.FindAsync(It.IsAny<object[]>())).ReturnsAsync((object[] ids) =>
      {
        var id = (Guid) ids.First();
        return users.FirstOrDefault(x => x.Id == id);
      });
```
I have added a unit test for `FindAsync` case as example: [DbSetFindAsyncUserEntity](https://github.com/romantitov/MockQueryable/blob/673dd6b0d9c9cadfedfdb858968455bcda480223/src/MockQueryable/MockQueryable.Sample/MyServiceMoqTests.cs#L315)
