### ISSUE TITLE
Mocking AddAsync

### ISSUE THREAD

**Issue by AdisonCavani** [romantitov/MockQueryable#61]
I need to mock ``AddAsync(obj)`` function.
I have seen [this](https://stackoverflow.com/questions/49142556/how-do-i-mock-addasync) stackoverflow topic, but proposed code: 
```cs
mockWebJobDbSet
    .Setup(_ => _.AddAsync(It.IsAny<WebJobStatus>(), It.IsAny<System.Threading.CancellationToken>()))
    .Callback((WebJobStatus model, CancellationToken token) => { webjobstatusList.Add(model); })
    .Returns((WebJobStatus model, CancellationToken token) => Task.FromResult((EntityEntry<WebJobStatus>)null));
```
will return **null** ``EntityEntry<WebJobStatus>`` which will cause to fail my unit test.

Function I want to test:
```cs
Url obj = new()
{
    FullUrl = url
};

var savedObj = await _context.Url.AddAsync(obj);

return savedObj.Entity.Id
```
Error: ``savedObj`` is null

**Comment by romantitov** [comment]
Hello @AdisonCavani thank you for your feedback. 
`savedObj` is null because in `.Returns((WebJobStatus model, CancellationToken token) => Task.FromResult((EntityEntry<WebJobStatus>)null));` you defined to return `null` for result of any `AddAsync` operation. You need to receive result from AddAsync not equal to `null` you have to define it in `.Returns...`
To make it work you can just it according to [the answer](https://stackoverflow.com/a/71344463/1412592).
